### ISSUE TITLE
Roadmap to accomplish the CDC update/delete in iceberg. (Phrase #1)

### ISSUE THREAD

**Issue by openinx** [generic-datalake/iceberg#28]
- [ ]  Define primary key specification in iceberg table format.
- [ ]  Define sorted specification in iceberg table format. 
- [ ]  Define delete files format/specification in iceberg table format.
- [ ]  Define/implement the iceberg table UPDATE/DELETE path (Streaming Write Path) 
- [ ]  Implement JOIN between base data file and delta files. (Batch Read Path)
- [ ]  Incremental consume the newly written delta files (Streaming Read Path)
- [ ]  TTL to expire to snapshots. 
- [ ]  Implement minor compaction to merge small delta files into bigger delta files to reduce the small files.
- [ ] Implement major compaction to merge base data files and delta files for removing delta files.
